// flow-typed signature: ebd043bebbb096f5766ec492daaabff8
// flow-typed version: <<STUB>>/graphqlgen_v^0.6.0-rc9/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphqlgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphqlgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphqlgen/dist/generators/common' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/common.spec' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/flow/generator' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/flow/scaffolder' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/reason/generator' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/reason/scaffolder' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/typescript/generator' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/generators/typescript/scaffolder' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/glob' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/index' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/factory' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/flow-ast' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/index' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/ts-ast' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/types' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/introspection/utils' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/output' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/parse' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/path-helpers' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/project-output' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/source-helper' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/types' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/utils' {
  declare module.exports: any;
}

declare module 'graphqlgen/dist/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphqlgen/dist/generators/common.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/common'>;
}
declare module 'graphqlgen/dist/generators/common.spec.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/common.spec'>;
}
declare module 'graphqlgen/dist/generators/flow/generator.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/flow/generator'>;
}
declare module 'graphqlgen/dist/generators/flow/scaffolder.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/flow/scaffolder'>;
}
declare module 'graphqlgen/dist/generators/reason/generator.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/reason/generator'>;
}
declare module 'graphqlgen/dist/generators/reason/scaffolder.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/reason/scaffolder'>;
}
declare module 'graphqlgen/dist/generators/typescript/generator.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/typescript/generator'>;
}
declare module 'graphqlgen/dist/generators/typescript/scaffolder.js' {
  declare module.exports: $Exports<'graphqlgen/dist/generators/typescript/scaffolder'>;
}
declare module 'graphqlgen/dist/glob.js' {
  declare module.exports: $Exports<'graphqlgen/dist/glob'>;
}
declare module 'graphqlgen/dist/index.js' {
  declare module.exports: $Exports<'graphqlgen/dist/index'>;
}
declare module 'graphqlgen/dist/introspection/factory.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/factory'>;
}
declare module 'graphqlgen/dist/introspection/flow-ast.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/flow-ast'>;
}
declare module 'graphqlgen/dist/introspection/index.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/index'>;
}
declare module 'graphqlgen/dist/introspection/ts-ast.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/ts-ast'>;
}
declare module 'graphqlgen/dist/introspection/types.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/types'>;
}
declare module 'graphqlgen/dist/introspection/utils.js' {
  declare module.exports: $Exports<'graphqlgen/dist/introspection/utils'>;
}
declare module 'graphqlgen/dist/output.js' {
  declare module.exports: $Exports<'graphqlgen/dist/output'>;
}
declare module 'graphqlgen/dist/parse.js' {
  declare module.exports: $Exports<'graphqlgen/dist/parse'>;
}
declare module 'graphqlgen/dist/path-helpers.js' {
  declare module.exports: $Exports<'graphqlgen/dist/path-helpers'>;
}
declare module 'graphqlgen/dist/project-output.js' {
  declare module.exports: $Exports<'graphqlgen/dist/project-output'>;
}
declare module 'graphqlgen/dist/source-helper.js' {
  declare module.exports: $Exports<'graphqlgen/dist/source-helper'>;
}
declare module 'graphqlgen/dist/types.js' {
  declare module.exports: $Exports<'graphqlgen/dist/types'>;
}
declare module 'graphqlgen/dist/utils.js' {
  declare module.exports: $Exports<'graphqlgen/dist/utils'>;
}
declare module 'graphqlgen/dist/validation.js' {
  declare module.exports: $Exports<'graphqlgen/dist/validation'>;
}
