// flow-typed signature: 6f88965eee1554b550d2a949a2c02aeb
// flow-typed version: <<STUB>>/prisma-cli_v^1.0.9/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma-cli/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prisma-cli/dist/index.js' {
  declare module.exports: $Exports<'prisma-cli/dist/index'>;
}
