// flow-typed signature: 1fd7f4f8c1a687c55c6f624c5dd7403c
// flow-typed version: <<STUB>>/sha256_v^0.2.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sha256'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sha256' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sha256/lib/nodecrypto' {
  declare module.exports: any;
}

declare module 'sha256/lib/sha256' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sha256/lib/nodecrypto.js' {
  declare module.exports: $Exports<'sha256/lib/nodecrypto'>;
}
declare module 'sha256/lib/sha256.js' {
  declare module.exports: $Exports<'sha256/lib/sha256'>;
}
